version: '3.9'

services:
  bot:
    container_name: 'oilPrice'
    image: oilprice
    build:
      context: ..
      dockerfile: bot/Dockerfile
    restart: unless-stopped
    volumes:
      - oilPriceDb:/db/

volumes:
  oilPriceDb:
